networks:
  app-network:
    driver: bridge

services:
  api-backend:
    container_name: api-backend
    build:
      context: ./repositories
      dockerfile: ./Dockerfile_apiBackend
    volumes:
      - ./repositories/api-backend:/app
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      - CORE_RDB_HOST=db
      - CORE_RDB_DATABASE=${DB_NAME}
      - CORE_RDB_USER=${DB_USER}
      - CORE_RDB_PASSWORD=${DB_PASSWORD}

  web-frontend:
    container_name: web-frontend
    build:
      context: ./repositories
      dockerfile: ./Dockerfile_webFrontend
    volumes:
      - ./repositories/web-frontend:/app
    ports:
      - "5173:5173"
    environment:
      - API_BASE_URL=http://localhost:8080